# @file  Makefile
# @brief Arquivo Make
# @date 22/04/2022
# @author GRR20190372 - Jorge Lucas Vicilli Jabczenski

CXXFLAGS= -Wall 
CC= g++

all : escalona 

escalona : transactions.o graph.o utils.o escalona.o

clean :
	$(RM) *.o

purge:
	$(RM) escalona *.o